/*
 * PROPRIETARY INFORMATION.  This software is proprietary to
 * Side Effects Software Inc., and is not to be reproduced,
 * transmitted, or disclosed in any way without written permission.
 *
 * Produced by:
 *      Side Effects Software Inc
 *      123 Front Street West, Suite 1401
 *      Toronto, Ontario
 *      Canada   M5J 2M2
 *      416-504-9876
 *
 * COMMENTS:
 *      Generated version information to be used when linking for sanity checks.
 */

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// WARNING! This file is GENERATED by Make.
// DO NOT modify manually or commit to the repository!
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Versions

public struct HAPI_Version
{
	public const int HOUDINI_MAJOR			= 13;
	public const int HOUDINI_MINOR			= 5;
	public const int HOUDINI_BUILD			= 137;

	public const int ORIG_HOUDINI_MAJOR		= 13;
	public const int ORIG_HOUDINI_MINOR		= 5;
	public const int ORIG_HOUDINI_BUILD		= 137;

	public const int HOUDINI_ENGINE_MAJOR	= 1;
	public const int HOUDINI_ENGINE_MINOR	= 7;
	
	public const int HOUDINI_ENGINE_API		= 11;
};
